site_name: desafio-vue
site_description: Desafio Vue
repo_url: https://github.com/hernanramirez/desafio-vue
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/hernanramirez">hernanramirez</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
